### PR TITLE
setOnNotificationsChange Updated to carry payload

### PR DESCRIPTION
**Pull request by riquelme-stripe**
Previous definition was empty. Updating to actual API Review functionality.

### CODE REVIEW

**Comment by hliana-stripe** [comment]
can we include a screen recording of this working in forever? (console log is fine to show that we see the total/action required being passed thru)

**Comment by riquelme-stripe** [comment]
The rendering behavior isn't fully ready yet as you can see but everything is working as it should behind the hood.
https://github.com/stripe/connect-js/assets/170659229/ece03147-9472-48ba-8abd-32228b4a877e

**Comment by riquelme-stripe** [comment]
https://github.com/stripe/connect-js/assets/170659229/e569c94f-a598-4e13-97fc-19dfe18c8ca4

**Review by hliana-stripe — APPROVED** [review]
awesome, thx for the screenrecording! - make sure to include this change in beta as well

**Pull request merged**
